#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Auto start
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh 

# Language layout
setxkbmap -model pc104 -layout us,bg -variant ,, -option grp:alt_shift_toggle 

# XInput Devices
# Touchpad
xinput set-prop "ELAN0504:00 04F3:303F Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0504:00 04F3:303F Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ELAN0504:00 04F3:303F Touchpad" "libinput Accel Speed" 0.3

# Logitech MX Master 3S
xinput set-prop "Logitech MX Master 3S" "libinput Natural Scrolling Enabled" 1
xinput set-prop "Logitech MX Master 3S" "libinput Accel Speed" -0.8
